Implement password toggle visibility
edgar-zigis/MaterialTextField pull request #8
Opened 2020-11-06 02:12 UTC by gilbertparreno

2020-11-08 19:26 UTC, edgar-zigis requested changes

2020-11-08 19:26 UTC, edgar-zigis commented on app/src/main/res/layout/activity_main.xml
> +            app:togglePasswordVisibility="true"
please format xml and sort parameters

2020-11-08 19:27 UTC, edgar-zigis commented
Please merge with master as there are now some conflicts.

2020-11-09 03:27 UTC, gilbertparreno commented on app/src/main/res/layout/activity_main.xml
> +            app:togglePasswordVisibility="true"
fixed

2020-11-09 11:54 UTC, edgar-zigis approved these changes

2020-11-09 11:55 UTC, merged